#!/bin/bash -l

#$ -N myjob
#$ -m e
#$ -pe mpi_16_tasks_per_node 16

########### Description of code #############################
# Extract barcodes from each run, and count the number of reads
# per distinct barcode. For each run, plot the cumulative
# distribution and retrieve whitelist

# Load modules
module unload anaconda3
module load python3/3.6.5
module load umitools/1.0.0

samples=/projectnb/bf528/project_4_scrnaseq/fastq

# concatenating all runs into one file
zcat $samples/SRR3879604/SRR3879604_1_bc.fastq.gz \
$samples/SRR3879605/SRR3879605_1_bc.fastq.gz \
$samples/SRR3879606/SRR3879606_1_bc.fastq.gz > total_1_bc.fastq

# Identify correct cell barcodes
awk '{if(NR%4==2){print substr($1,1,19)}}' total_1_bc.fastq | sort | uniq -c > merged_counts.txt